config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :reviews do
    resources :comments
    resource :bookmark
  end

  resources :users

  resource :session

  root "reviews#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :review, uniqueness: { scope: :user }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :body, presence: true

end

app/models/review.rb
class Review < ApplicationRecord

  has_many :comments
  belongs_to :user
  has_many :bookmarks

  geocoded_by :address
  after_validation :geocode


  #validates :title, presence: true
  validates :body, length: { minimum: 10 }, allow_blank: true
  validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }, allow_nil: true
  #validates :restaurant, presence: true
  #validates :ambience, presence:true
  validates :phone_number, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format" }, allow_blank: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 3 }, allow_nil: true
  #validates :address, presence: true

  def to_param
    id.to_s + "-" + title.parameterize
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :reviews
  has_many :comments
  has_many :bookmarks

  validates :username, presence: true, uniqueness: true
  validates :email, presence:true, uniqueness: true

  def to_param
    username
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :find_current_user

  helper_method :is_logged_in?
  #allows you to use this in views from the application controller

  def find_current_user
    if is_logged_in?
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def check_login
    # if is_logged_in?
    # #all cool, don't need to do anything
    # else
    #   redirect_to new_session_path
    unless is_logged_in?
      redirect_to new_session_path
    end
  end

  def is_logged_in?
    session[:user_id].present?
  end


end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :check_login

  def create

      @review = Review.find(params[:review_id])

      @bookmark = @review.bookmarks.new

      @bookmark.user = @current_user

      @bookmark.save

      redirect_to review_path(@review)
  end

  def destroy

    @review = Review.find(params[:review_id])

    if @review.bookmarks.where(user: @current_user).delete_all

    redirect_to review_path(@review)

  end

  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create

    @review = Review.find(params[:review_id])

    # take info from the form and add it to the db
    @comment = @review.comments.new(params.require(:comment).permit(:body))

    @comment.user = @current_user

    @comment.save

    redirect_to review_path(@review)


  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :check_login, except: [:index, :show]

  def index
    # this is our list page for our reviews

    # @number = rand(100)

    #@reviews = ["The Smile", "Baby Bo's", "Chipotle", "Albion", "McDonald's"]

    @price = params[:price]
    @cuisine = params[:cuisine]
    @location = params[:location]


    @reviews = Review.all

    if @price.present?
      @reviews = @reviews.where(price: @price)
    end

    if @cuisine.present?
      @reviews = @reviews.where(cuisine: @cuisine)
    end

    if @location.present?
      @reviews = @reviews.near(@location)
    end

    # if @price.present?
    #
    #   @reviews = Review.where(price: @price)
    #
    # else
    #
    #   @reviews = Review.all
    #
    #end

  end

  def new

    # the form for adding a new review
    @review = Review.new

  end

  def create

    # take info from the form and add it to the db
    @review = Review.new(form_params)

    @review.user = @current_user

    # we want to check if model can be saved
    if @review.save
      redirect_to root_path
    else
      render "new"
    end

  end

  def show

    #individual review page
    @review = Review.find(params[:id])

  end

  def destroy

    #find the inividual # REVIEW:
    @review = Review.find(params[:id])



    if @review.user == @current_user
      #destroy it
      @review.destroy

      #redirect back to home page
      redirect_to root_path
    else
      redirect_to review_path(@review)
    end

  end

  def edit

    @review = Review.find(params[:id])

    if @review.user != @current_user
      redirect_to review_path(@review)
    end

  end


  def update

    @review = Review.find(params[:id])

    if @review.user != @current_user
      redirect_to review_path(@review)
    else
      if @review.update(form_params)
        redirect_to review_path(@review)
      else
        render "edit"
      end
    end

    # @review.update(form_params)
    #
    # redirect_to review_path(@review)

  end

  def form_params

      params.require(:review).permit(:title, :restaurant, :body, :score, :ambience, :phone_number, :cuisine, :price, :address)

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new



  end

  def create

    @form_data = params.require(:session)

    @username = @form_data[:username]
    @password = @form_data[:password]

    @user = User.find_by(username: @username).try(:authenticate, @password)

    if @user

      session[:user_id] = @user.id

      redirect_to root_path
    else
      render "new"
    end

  end

  def destroy

    reset_session

    render "new"

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index

  @users = User.all

end

def new

  @user = User.new

end

def create

  @user = User.new(form_params)

  if @user.save

    session[:user_id] = @user.id

    redirect_to users_path
  else
    render "new"
  end

end

def show

  @user = User.find_by(username: params[:id])

end

def form_params

    params.require(:user).permit(:username, :password, :password_confirmation, :email)

end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> - Bien Reviews - The best restaurants in the world</title>
    <%= favicon_link_tag asset_path('bien-page-icon.svg') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <h1>

        <%= link_to root_path  do %>
          <%= image_tag "bien-logo.svg" %>
        <% end %>

      </h1>

      <nav>

        <% if is_logged_in? %>
          Hi, <%= @current_user.username %>
          <%= link_to "Add a review", new_review_path %>
          <%= link_to "Log out", session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_path %>
          <%= link_to "Log in", new_session_path %>
        <% end %>




      </nav>
    </header>

    <main>
    <%= yield %>
    </main>

    <footer>
      Copyright 2020 Bien Reviews
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>

  <% if @review.errors.any? %>

    <div class="errors">

      <% @review.errors.full_messages.each do |message| %>

        <p><%= message %></p>

      <% end %>

    </div>

  <% end %>


  <%= simple_form_for @review do |f| %>
    <%= f.input :title %>
    <%= f.input :restaurant %>
    <%= f.input :address %>
    <%= f.input :body %>
    <%= f.input :score %>
    <%= f.input :ambience %>
    <%= f.input :cuisine %>
    <%= f.input :price %>
    <%= f.input :phone_number, placeholder: "XXX-XXX-XXXX" %>
    <%= f.button :submit %>
  <% end %>


  <!-- <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :restaurant %>
    <%= f.text_field :restaurant %>
  </p>

  <p>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :score %>
    <%= f.number_field :score %>
  </p>

  <p>
    <%= f.label :ambience %>
    <%= f.text_field :ambience %>
  </p>

  <p>
    <%= f.label :cuisine %>
    <%= f.text_field :cuisine %>
  </p>

  <p>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </p>

  <p>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, placeholder: "XXX-XXX-XXXX"  %>
  </p>

  <p>
    <%= f.submit "Save review" %>
  </p>

<% end %> -->

app/views/reviews/edit.html.erb
<% content_for :page_title, "Update your review" %>

<h3>Edit your restaurant review</h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% content_for :page_title, "Bien Reviews - The best restaurants in the world" %>


<nav class="filters">

  <%= active_link_to "All", root_path, active: { price: nil, cuisine: nil, location: nil } %>

  <div>
  <%= active_link_to "$", root_path(price: 1, cuisine: @cuisine, location: @location), active: { price: 1 } %>
  <%= active_link_to "$$", root_path(price: 2, cuisine: @cuisine, location: @location), active: { price: 2 }  %>
  <%= active_link_to "$$$", root_path(price: 3, cuisine: @cuisine, location: @location), active: { price: 3 }  %>
  </div>

  <div>
  <%= active_link_to "Indian", root_path(cuisine: "Indian", price: @price, location: @location), active: { cuisine: "Indian" }  %>
  <%= active_link_to "Thai", root_path(cuisine: "Thai", price: @price, location: @location), active: { cuisine: "Thai" } %>
  <%= active_link_to "American", root_path(cuisine: "American", price: @price, location: @location), active: { cuisine: "American" } %>
  </div>

  <form action="/">
    <input type="text" name="location" placeholder="Search location..." value="<%= @location %>">
    <input type="hidden" name="price" value="<%= @price %>">
    <input type="hidden" name="cuisine" value="<%= @cuisine %>">
  </form>

</nav>

<% if @reviews.each do |review| %>
  <div class="review">
    <%= link_to review_path(review) do %>
      <h2><%= ProfanityFilter::Base.clean(review.title) %></h2>
      <p>
        <%= review.cuisine %> -
        <%= pluralize review.comments.count, "comment" %>
      </p>
    <% end %>
  </div>
<% end.empty? %>
  <h2>There are no reviews yet that match your search criteria.</h2>
<% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new review" %>

<h3>Add your new restaurant review</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title  %>

<h1><%= ProfanityFilter::Base.clean(@review.title) %></h1>
<h2><%= @review.restaurant %></h2>

<% if is_logged_in? %>
  <p>

      <% if @review.bookmarks.where(user: @current_user).any? %>
        <%= link_to "Unbookmark", review_bookmark_path(@review), method: :delete %>
      <% else %>
        <%= link_to "Bookmark", review_bookmark_path(@review), method: :post %>
      <% end %>
  </p>
<% end %>

<h3> Bookmarked by... </h3>

<ul>

  <% @review.bookmarks.each do |bookmark| %>

    <li><%= bookmark.user.username %></li>

  <% end %>

</ul>

<div class="address">
  Address: <%= @review.address %>
</div>


<div class="user">
  Posted by:
  <% if @review.user.present? %>
    <%= link_to @review.user.username, user_path(@review.user) %>
  <% else %>
    anonymouse <%= image_tag "noun_Mouse_1046559.svg" %>
  <% end %>
</div>

<div class="score">
  Score: <%= @review.score %>/10
</div>

<% if @review.ambience.present? %>
<div class="ambience">
  Ambience: <%= @review.ambience %>
</div>
<% end %>

<% if @review.cuisine.present? %>
<div class="cuisine">
  Cuisine: <%= @review.cuisine %>
</div>
<% end %>

<% if @review.price.present? %>
<div class="price">
  Price: <%= @review.price %>
</div>
<% end %>

<div class="body">
  <%= simple_format ProfanityFilter::Base.clean(@review.body) %>
</div>

<div class="phone_number">
  <%= @review.phone_number %>
</div>

<% if @review.user == @current_user %>
  <div class="actions">
    <%= link_to "Edit this review", edit_review_path(@review) %>
    <%= link_to "Delete this review", review_path(@review), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
<% else %>

<% end %>


<h3>Add a comment</h3>

<%= simple_form_for [@review, Comment.new] do |f| %>
  <%= f.input :body %>
  <%= f.button :submit, "Add comment" %>
<% end %>

<h3>Comments</h3>

<% @review.comments.order("created_at desc").each do |comment| %>

<div class="comment">
  <%= simple_format ProfanityFilter::Base.clean(comment.body) %>

  <p class="posted">Posted at <%= time_tag comment.created_at %></p>
  <p class="posted"> Posted by
    <% if comment.user.present? %>
      <%= link_to comment.user.username, user_path(comment.user) %></p>
    <% else %>
      anonymouse <%= image_tag "noun_Mouse_1046559.svg" %>
    <% end %>
</div>

<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>

    <div class="errors">

      <% @user.errors.full_messages.each do |message| %>

        <p><%= message %></p>

      <% end %>

    </div>

  <% end %>


  <%= simple_form_for @user do |f| %>
    <%= f.input :username %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.button :submit %>
  <% end %>

<% end %>

app/views/users/index.html.erb
  <h2>All Users</h2>

<% if @users.each do |user| %>
      <p>
        <%= user.username %> (<%= user.email %>)
      </p>
<% end.empty? %>
  <h3>Ain't no users here</h3>
<% end %>

app/views/users/new.html.erb
<% content_for :page_title, "Sign up" %>

<h2>Sign up</h2>

<%= render "form" %>

app/views/users/show.html.erb
<h2><%= @user.username %>'s page</h2>